export interface IReview {
  advantage: string,
  clickDisLike: boolean,
  clickLike: boolean,
  comments: string,
  created_at: number,
  design: any,
  disadvantages: string,
  dislakes: number,
  f_created_at: string,
  files: any,
  functional: any,
  id: number,
  likes: number,
  name: string,
  product_id: number,
  rate: number,
  udobstvo: any,
  user_id: number
}